// =====================================================================
// LESSON 232 — REACT + TYPESCRIPT — section overview.
// =====================================================================
//
// React and TypeScript are a common pairing in modern web development.
// This section covers how to use them together:
//   - Setting up a React + TypeScript project
//   - Typing React components (props, state, events)
//   - Common types you will encounter in React code
//   - Compiling and running the project
//
// PREREQUISITE: basic React knowledge. This section does NOT teach React
// from scratch — it only covers how to layer TypeScript on top of it.
// For learning React itself, see the official docs at https://react.dev
//
// =====================================================================
// LESSON 233 — CREATING THE PROJECT WITH VITE.
// =====================================================================
//
// This project was created using Vite's project scaffolder. To create
// a similar project from scratch, run:
//
//   npm create vite@latest
//
// Choose a name, then the "React" framework and the "TypeScript" variant.
// Vite generates a ready-to-use folder with tsconfig files, package.json
// (including @types/react(-dom) for TypeScript definitions), a src/ demo
// app, and Vite/ESLint config.
//
// REACT VERSION: if the template uses an older React, upgrade with:
//   npm install react@latest react-dom@latest
//   npm install -D @types/react@latest @types/react-dom@latest
// (This project is already on React 19.)
//
// SCRIPTS:
//   npm run dev     — dev server with hot-reload at http://localhost:5173
//                     (TypeScript is compiled on the fly in the background)
//   npm run build   — production bundle with full TS → JS compilation
//   npm run preview — serve the production build locally
//
// =====================================================================
// LESSON 234 — BUILDING A FIRST TYPED COMPONENT.
// =====================================================================
//
// PROJECT CLEANUP: the demo files generated by Vite (App.css, react.svg,
// and the boilerplate App.tsx content) are removed or simplified. A new
// shared stylesheet (index.css) and an image (goals.jpg) are added.
// This gives us a clean slate to start building typed React components.
//
// THE .tsx EXTENSION:
// Regular TypeScript files use ".ts". Files that contain JSX (React's
// HTML-like syntax inside function bodies) use ".tsx" instead — the "x"
// signals JSX support. This is analogous to how plain React files use
// ".jsx" instead of ".js".
//
// =====================================================================
// LESSON 235 — USING THE TYPED COMPONENT & VITE IMAGE IMPORTS.
// =====================================================================
//
// IMPORTING LOCAL IMAGES IN VITE:
// In plain JavaScript, you cannot "import" an image file — imports only
// work for JavaScript modules. Vite extends this by rewriting image
// imports at build time: the import expression yields the PUBLIC URL
// of the asset after bundling (e.g., "/assets/goals-ab12cd.jpg"),
// suitable for use in <img src>.
//
// This is a Vite convenience, not a TypeScript or vanilla JS feature.
//
// FILE EXTENSIONS IN IMPORT PATHS:
// You can write the import as './components/Header' or
// './components/Header.tsx' — both work. Include the extension if your
// team prefers explicit paths; omit it to rely on resolution. The only
// rule: do NOT use ".jsx" or ".js" — stick with ".tsx" or no extension.
//
// TYPE CHECKING AT THE CALL SITE:
// Because Header's props parameter is typed as HeaderProps, TypeScript
// verifies that we pass a matching object. Omitting the "image" prop,
// misspelling "src", or passing a non-string would all be compile errors
// — the same type safety you get for function calls.
//
// =====================================================================
// LESSON 236 — PASSING CONTENT VIA THE children PROP.
// =====================================================================
//
// Anything placed between the opening and closing tags of a component
// is automatically delivered to that component as its "children" prop.
// Here, the <h1> element becomes the "children" of <Header>, which
// renders it inside its own <header> wrapper (see Header.tsx).
//
// Because the "children" prop on HeaderProps is optional (declared with
// "?"), Header can also be used WITHOUT nested content — TypeScript
// will not complain. If "children" were required (no "?"), omitting
// the inner content would produce a compile error.

import Header from './components/Header.tsx';
import goalsImg from './assets/goals.jpg';

function App() {
  return (
    <main>
      <Header image={{ src: goalsImg, alt: 'A list of goals.' }}>
        <h1>Your Course Goals</h1>
      </Header>
    </main>
  );
}

export default App;
