// =====================================================================
// LESSON 232 — REACT + TYPESCRIPT — section overview.
// =====================================================================
//
// React and TypeScript are a common pairing in modern web development.
// This section covers how to use them together:
//   - Setting up a React + TypeScript project
//   - Typing React components (props, state, events)
//   - Common types you will encounter in React code
//   - Compiling and running the project
//
// PREREQUISITE: basic React knowledge. This section does NOT teach React
// from scratch — it only covers how to layer TypeScript on top of it.
// For learning React itself, see the official docs at https://react.dev
//
// =====================================================================
// LESSON 233 — CREATING THE PROJECT WITH VITE.
// =====================================================================
//
// This project was created using Vite's project scaffolder. To create
// a similar project from scratch, run:
//
//   npm create vite@latest
//
// Choose a name, then the "React" framework and the "TypeScript" variant.
// Vite generates a ready-to-use folder with tsconfig files, package.json
// (including @types/react(-dom) for TypeScript definitions), a src/ demo
// app, and Vite/ESLint config.
//
// REACT VERSION: if the template uses an older React, upgrade with:
//   npm install react@latest react-dom@latest
//   npm install -D @types/react@latest @types/react-dom@latest
// (This project is already on React 19.)
//
// SCRIPTS:
//   npm run dev     — dev server with hot-reload at http://localhost:5173
//                     (TypeScript is compiled on the fly in the background)
//   npm run build   — production bundle with full TS → JS compilation
//   npm run preview — serve the production build locally
//
// =====================================================================
// LESSON 234 — BUILDING A FIRST TYPED COMPONENT.
// =====================================================================
//
// PROJECT CLEANUP: the demo files generated by Vite (App.css, react.svg,
// and the boilerplate App.tsx content) are removed or simplified. A new
// shared stylesheet (index.css) and an image (goals.jpg) are added.
// This gives us a clean slate to start building typed React components.
//
// THE .tsx EXTENSION:
// Regular TypeScript files use ".ts". Files that contain JSX (React's
// HTML-like syntax inside function bodies) use ".tsx" instead — the "x"
// signals JSX support. This is analogous to how plain React files use
// ".jsx" instead of ".js".
//
// =====================================================================
// LESSON 235 — USING THE TYPED COMPONENT & VITE IMAGE IMPORTS.
// =====================================================================
//
// IMPORTING LOCAL IMAGES IN VITE:
// In plain JavaScript, you cannot "import" an image file — imports only
// work for JavaScript modules. Vite extends this by rewriting image
// imports at build time: the import expression yields the PUBLIC URL
// of the asset after bundling (e.g., "/assets/goals-ab12cd.jpg"),
// suitable for use in <img src>.
//
// This is a Vite convenience, not a TypeScript or vanilla JS feature.
//
// FILE EXTENSIONS IN IMPORT PATHS:
// You can write the import as './components/Header' or
// './components/Header.tsx' — both work. Include the extension if your
// team prefers explicit paths; omit it to rely on resolution. The only
// rule: do NOT use ".jsx" or ".js" — stick with ".tsx" or no extension.
//
// TYPE CHECKING AT THE CALL SITE:
// Because Header's props parameter is typed as HeaderProps, TypeScript
// verifies that we pass a matching object. Omitting the "image" prop,
// misspelling "src", or passing a non-string would all be compile errors
// — the same type safety you get for function calls.
//
// =====================================================================
// LESSON 236 — PASSING CONTENT VIA THE children PROP.
// =====================================================================
//
// Anything placed between the opening and closing tags of a component
// is automatically delivered to that component as its "children" prop.
// Here, the <h1> element becomes the "children" of <Header>, which
// renders it inside its own <header> wrapper (see Header.tsx).
//
// Because the "children" prop on HeaderProps is optional (declared with
// "?"), Header can also be used WITHOUT nested content — TypeScript
// will not complain. If "children" were required (no "?"), omitting
// the inner content would produce a compile error.

// =====================================================================
// LESSON 237 — RENDERING A LIST OF GOALS.
// =====================================================================
//
// We use the CourseGoals component and pass an array of goal objects
// as its "goals" prop. TypeScript verifies that each object matches
// the "Goal" shape declared in CourseGoals.tsx — missing fields or
// wrong types would be compile errors at this call site.
//
// =====================================================================
// LESSON 239 — MANAGING THE GOALS LIST AS STATE.
// =====================================================================
//
// The goals list is no longer a static literal — it is managed by
// React's useState hook. This allows us to change the list at runtime
// (add or delete goals) and have React re-render the UI automatically.
//
// WHY STATE LIVES IN App, NOT IN CourseGoals:
// We will soon need to mutate the list from a SIBLING component (the
// form for creating new goals). State in React flows DOWN through
// props, so we must "lift" the state up to the nearest common
// ancestor — App — that owns both children. This is a standard
// React pattern, not TypeScript-specific.
//
// TYPING useState:
// useState is a GENERIC function. It can be called in two ways:
//
//   1. Pass the state type as a type parameter in angle brackets:
//        const [goals, setGoals] = useState<Goal[]>([]);
//      Useful when the initial value alone is ambiguous (e.g., an empty
//      array could be any element type).
//
//   2. Let TypeScript INFER the type from a concrete initial value:
//        useState([{ id: 1, ... }])   ← inferred as the shape of the literal
//      Works well when the initial value is unambiguous.
//
// Below, we use option 2: the initial array contains two concrete goal
// objects, so TypeScript infers the state type as an array of objects
// with id/title/description fields. That inferred shape happens to
// match the "Goal" type in CourseGoals, so passing "goals" to the
// "goals" prop type-checks correctly.
//
// useState returns a TUPLE: [currentValue, setterFunction]. The setter
// triggers a re-render when called with a new value.

import { useState } from 'react';
import Header from './components/Header.tsx';
import CourseGoals from './components/CourseGoals.tsx';
import NewGoal from './components/NewGoal.tsx';
import goalsImg from './assets/goals.jpg';

// =====================================================================
// LESSON 240 — DELETE HANDLER WITH FUNCTIONAL STATE UPDATE.
// =====================================================================
//
// The handleDeleteGoal function signature must match the onDelete
// prop's function type declared in CourseGoalsProps: it takes an id
// (number) and returns nothing. TypeScript checks this match at the
// call site — passing a mismatched function would be a compile error.
//
// FUNCTIONAL STATE UPDATE:
// Whenever new state depends on the PREVIOUS state, React recommends
// passing a FUNCTION (not a plain value) to the state setter:
//
//   setGoals((prevGoals) => ...)
//
// React invokes this updater with the latest state snapshot, avoiding
// stale-closure bugs when multiple updates are queued. TypeScript
// automatically infers "prevGoals" as the same type as the state.
//
// IMMUTABLE UPDATE WITH filter():
// The updater returns a NEW array produced by Array.prototype.filter,
// keeping only goals whose id does not match the deleted id. Returning
// true from the predicate keeps an element; returning false drops it.
// Using filter (instead of splice) keeps the original array untouched —
// React requires a new reference to detect the state change.
//
// PASSING THE FUNCTION (NOT CALLING IT):
// onDelete={handleDeleteGoal}   ← correct: passes the function reference
// onDelete={handleDeleteGoal(1)} ← wrong: calls it immediately and
//                                  passes the return value (undefined)

function App() {
  const [goals, setGoals] = useState([
    {
      id: 1,
      title: 'Learn TS',
      description: 'Learn TypeScript from the ground up',
    },
    {
      id: 2,
      title: 'Practice TS',
      description: 'Practice working with TypeScript',
    },
  ]);

  function handleDeleteGoal(id: number) {
    setGoals((prevGoals) => prevGoals.filter((goal) => goal.id !== id));
  }

  // =====================================================================
  // LESSON 243 — ADDING A NEW GOAL.
  // =====================================================================
  //
  // The parameters (text, summary) match the signature declared in
  // NewGoalProps.onAdd — TypeScript enforces that match at the point
  // where we pass handleAddGoal to the NewGoal component.
  //
  // IMMUTABLE UPDATE WITH concat():
  // Array.concat returns a NEW array that includes all existing items
  // plus the new one. Returning a new array (instead of .push()-ing
  // into the old one) is important — React compares references to
  // detect changes, so mutating in place would fail to trigger re-render.
  //
  // TYPESCRIPT CATCHES STRUCTURAL MISMATCHES:
  // The new goal object's keys must exactly match the state's inferred
  // shape (id/title/description). Using a wrong name (e.g., "summary"
  // instead of "description") surfaces as an "Object literal may only
  // specify known properties" error — TypeScript preventing a subtle
  // bug before it reaches runtime.
  //
  // Math.random() is used for a quick id. In real apps prefer a proper
  // unique id (e.g., crypto.randomUUID()) to avoid collisions.
  function handleAddGoal(text: string, summary: string) {
    setGoals((prevGoals) =>
      prevGoals.concat({
        id: Math.random(),
        title: text,
        description: summary,
      })
    );
  }

  return (
    <main>
      <Header image={{ src: goalsImg, alt: 'A list of goals.' }}>
        <h1>Your Course Goals</h1>
      </Header>
      <NewGoal onAdd={handleAddGoal} />
      <CourseGoals goals={goals} onDelete={handleDeleteGoal} />
    </main>
  );
}

export default App;

// =====================================================================
// LESSON 245 — SECTION WRAP-UP.
// =====================================================================
//
// This section introduced the building blocks of using React with
// TypeScript:
//
//   - Project setup with Vite (npm create vite@latest, React+TS template)
//   - Typing component props using "type" or "interface"
//   - Destructuring props in the function signature
//   - The special "children" prop (ReactNode from React)
//   - Rendering lists of typed data with the required "key" prop
//   - Component-to-parent communication via function props
//   - State management with useState (inference vs explicit generics)
//   - Lifting state up to a common ancestor
//   - Typed form event handlers (FormEvent<HTMLFormElement>)
//   - Reading form values with typed refs (useRef<HTMLInputElement>(null))
//   - Functional, immutable state updates (filter / concat) that React
//     can detect for re-rendering
//
// These are the core patterns you will use in most React + TypeScript
// projects. More advanced topics (context, reducers, custom hooks,
// generic components, higher-order components, utility types like
// ComponentProps, discriminated prop unions, etc.) are out of scope
// for this section.
//
// For further learning:
//   - Official React docs:                https://react.dev
//   - The instructor's full React course: "React - The Complete Guide"
//   - A dedicated React + TypeScript course also exists for deeper dives.
