// =====================================================================
// LESSON 232 — REACT + TYPESCRIPT — section overview.
// =====================================================================
//
// React and TypeScript are a common pairing in modern web development.
// This section covers how to use them together:
//   - Setting up a React + TypeScript project
//   - Typing React components (props, state, events)
//   - Common types you will encounter in React code
//   - Compiling and running the project
//
// PREREQUISITE: basic React knowledge. This section does NOT teach React
// from scratch — it only covers how to layer TypeScript on top of it.
// For learning React itself, see the official docs at https://react.dev
//
// =====================================================================
// LESSON 233 — CREATING THE PROJECT WITH VITE.
// =====================================================================
//
// This project was created using Vite's project scaffolder. To create
// a similar project from scratch, run:
//
//   npm create vite@latest
//
// Choose a name, then the "React" framework and the "TypeScript" variant.
// Vite generates a ready-to-use folder with tsconfig files, package.json
// (including @types/react(-dom) for TypeScript definitions), a src/ demo
// app, and Vite/ESLint config.
//
// REACT VERSION: if the template uses an older React, upgrade with:
//   npm install react@latest react-dom@latest
//   npm install -D @types/react@latest @types/react-dom@latest
// (This project is already on React 19.)
//
// SCRIPTS:
//   npm run dev     — dev server with hot-reload at http://localhost:5173
//                     (TypeScript is compiled on the fly in the background)
//   npm run build   — production bundle with full TS → JS compilation
//   npm run preview — serve the production build locally
//
// =====================================================================
// LESSON 234 — BUILDING A FIRST TYPED COMPONENT.
// =====================================================================
//
// PROJECT CLEANUP: the demo files generated by Vite (App.css, react.svg,
// and the boilerplate App.tsx content) are removed or simplified. A new
// shared stylesheet (index.css) and an image (goals.jpg) are added.
// This gives us a clean slate to start building typed React components.
//
// THE .tsx EXTENSION:
// Regular TypeScript files use ".ts". Files that contain JSX (React's
// HTML-like syntax inside function bodies) use ".tsx" instead — the "x"
// signals JSX support. This is analogous to how plain React files use
// ".jsx" instead of ".js".
//
// The simplified App.tsx below returns a plain string — a minimal
// starting point before we begin assembling real components. See
// components/Header.tsx for the first typed component.

function App() {
  return <>Hello World</>;
}

export default App;
